### PR TITLE
Update script.js to fix bug with artifacts URL, fixes #30

### LINKED ISSUE #30: Specified artifacts file in form doesn't actually pull the artifacts correctly
I'm trying to use DrupalPod to launch a "ddevdemo" site with a pre-populated database and files directory.

The repositories are:

- https://github.com/ultimike/ddevdemo
- https://github.com/ultimike/ddevdemo-artifacts

But, whenever I try to launch the site, the database and files directory are not automatically imported. I'm pretty sure I'm following the instructions from https://github.com/ddev/ddev-gitpod-launcher, but clearly I'm missing something...

thanks,
-mike

### PR DESCRIPTION
**Pull request by ultimike**
## The Issue
See #30.

## How This PR Solves The Issue
I _think_ that all that is needed is an additional `computeLink();` call, as I added in this PR, but additional testings by others is more than welcome.

## Manual Testing Instructions
Use a custom repository and artifacts URL  (not `d10simple`) and ensure it works.

-mike

### CODE REVIEW

**Comment by rfay** [comment]
But what about
* https://github.com/ddev/ddev-gitpod-launcher/pull/32 

?

**Comment by rfay** [comment]
Please add manual testing instructions as well. I don't remember how to manually test the form.

**Comment by rfay** [comment]
Gave you privs on this repo.

**Comment by rfay** [comment]
This can be previewed at https://htmlpreview.github.io/?https://github.com/ultimike/ddev-gitpod-launcher/blob/patch-2/docs/index.html

Thanks to https://stackoverflow.com/a/12233684/215713

**Comment by rfay** [comment]
Thanks for this! Used the more extensive
* https://github.com/ddev/ddev-gitpod-launcher/pull/32

instead, future PRs and improvements are all welcome.

**Comment by ultimike** [comment]
Thanks for taking care of this!

-mike

**Pull request closed without merging**
