### PR TITLE
Refactor computeLink function and event listeners, fixes #30

### LINKED ISSUE #30: Specified artifacts file in form doesn't actually pull the artifacts correctly
I'm trying to use DrupalPod to launch a "ddevdemo" site with a pre-populated database and files directory.

The repositories are:

- https://github.com/ultimike/ddevdemo
- https://github.com/ultimike/ddevdemo-artifacts

But, whenever I try to launch the site, the database and files directory are not automatically imported. I'm pretty sure I'm following the instructions from https://github.com/ddev/ddev-gitpod-launcher, but clearly I'm missing something...

thanks,
-mike

### PR DESCRIPTION
**Pull request by shaal**
I updated the `Pages` settings of my repo, you can test it here -
https://shaal.github.io/ddev-gitpod-launcher/

Notice that with this PR every keystroke immediately updates the link.

Fixes 
* https://github.com/ddev/ddev-gitpod-launcher/issues/30

### CODE REVIEW

**Comment by rfay** [comment]
Thanks so much for this. Does this mean that in the entire history of this ddev-gitpod-launcher it always failed and nobody ever reported the failure?

**Comment by rfay** [comment]
Gave you full privs on this repo.

**Comment by rfay** [comment]
But of course please see much simpler
* https://github.com/ddev/ddev-gitpod-launcher/pull/33

Also please provide manual testing instructions.

**Comment by shaal** [comment]
@rfay I added now testing steps in the description

**Comment by ultimike** [comment]
Thanks to you both for fixing this :)

-mike

**Pull request merged**
